package com.cf.client.poloniex.enums;

/**
 *
 * @author samuelfac
 *
 */
public enum CurrencyEnum {
    
    ONECR(1,"1CRedit"),               
    ABY(2,"ArtByte"),               
    AC(3,"AsiaCoin"),               
    ACH(4,"Altcoin Herald"),        
    ADN(5,"Aiden"),                 
    AEON(6,"AEON Coin"),            
    AERO(7,"Aerocoin"),             
    AIR(8,"AIRcoin"),               
    AMP(275,"Synereo AMP"),         
    APH(9,"AphroditeCoin"),         
    ARCH(258,"ARCHcoin"),           
    ARDR(285,"Ardor"),              
    AUR(10,"Auroracoin"),           
    AXIS(11,"Axis"),                
    BALLS(12,"Snowballs"),          
    BANK(13,"BankCoin"),            
    BBL(14,"BitBlock"),             
    BBR(15,"Boolberry"),            
    BCC(16,"BTCtalkcoin"),          
    BCH(292,"Bitcoin Cash"),        
    BCN(17,"Bytecoin"),             
    BCY(269,"BitCrystals"),         
    BDC(18,"Black Dragon Coin"),    
    BDG(19,"Badgercoin"),           
    BELA(20,"Bela"),                
    BITCNY(273,"BitCNY"),           
    BITS(21,"Bitstar"),             
    BITUSD(272,"BitUSD"),           
    BLK(22,"BlackCoin"),            
    BLOCK(23,"Blocknet"),           
    BLU(24,"BlueCoin"),             
    BNS(25,"BonusCoin"),            
    BONES(26,"Bones"),              
    BOST(27,"BoostCoin"),           
    BTC(28,"Bitcoin"),              
    BTCD(29,"BitcoinDark"),         
    BTCS(30,"Bitcoin-sCrypt"),      
    BTM(31,"Bitmark"),              
    BTS(32,"BitShares"),            
    BURN(33,"BurnerCoin"),          
    BURST(34,"Burst"),              
    C2(35,"Coin2.0"),               
    CACH(36,"CACHeCoin"),           
    CAI(37,"CaiShen"),              
    CC(38,"Colbert Coin"),          
    CCN(39,"Cannacoin"),            
    CGA(40,"Cryptographic Anomaly"),
    CHA(41,"Chancecoin"),           
    CINNI(42,"CinniCoin"),          
    CLAM(43,"CLAMS"),               
    CNL(44,"ConcealCoin"),          
    CNMT(45,"Coinomat1"),           
    CNOTE(46,"C-Note"),             
    COMM(47,"CommunityCoin"),       
    CON(48,"Coino"),                
    CORG(49,"CorgiCoin"),           
    CRYPT(50,"CryptCoin"),          
    CURE(51,"Curecoin"),            
    CVC(294,"Civic"),               
    CYC(52,"Conspiracy Coin"),      
    DAO(279,"The DAO"),             
    DASH(60,"Dash"),                
    DCR(277,"Decred"),              
    DGB(53,"DigiByte"),             
    DICE(54,"NeoDICE"),             
    DIEM(55,"Diem"),                
    DIME(56,"Dimecoin"),            
    DIS(57,"DistroCoin"),           
    DNS(58,"BitShares DNS"),        
    DOGE(59,"Dogecoin"),            
    DRKC(61,"DarkCash"),            
    DRM(62,"Dreamcoin"),            
    DSH(63,"Dashcoin"),             
    DVK(64,"DvoraKoin"),            
    EAC(65,"EarthCoin"),            
    EBT(66,"EBTcoin"),              
    ECC(67,"ECCoin"),               
    EFL(68,"Electronic Gulden"),    
    EMC2(69,"Einsteinium"),         
    EMO(70,"EmotiCoin"),            
    ENC(71,"Entropycoin"),          
    ETC(283,"Ethereum Classic"),    
    ETH(267,"Ethereum"),            
    eTOK(72,"eToken"),              
    EXE(73,"Execoin"),              
    EXP(270,"Expanse"),             
    FAC(74,"Faircoin"),             
    FCN(75,"Fantomcoin"),           
    FCT(271,"Factom"),              
    FIBRE(76,"Fibrecoin"),          
    FLAP(77,"FlappyCoin"),          
    FLDC(78,"FoldingCoin"),         
    FLO(254,"Florincoin"),          
    FLT(79,"FlutterCoin"),          
    FOX(80,"FoxCoin"),              
    FRAC(81,"Fractalcoin"),         
    FRK(82,"Franko"),               
    FRQ(83,"FairQuark"),            
    FVZ(84,"FVZCoin"),              
    FZ(85,"Frozen"),                
    FZN(86,"Fuzon"),                
    GAME(93,"GameCredits"),         
    GAP(87,"Gapcoin"),              
    GAS(296,"Gas"),                 
    GDN(88,"Global Denomination"),  
    GEMZ(89,"GetGems"),             
    GEO(90,"GeoCoin"),              
    GIAR(91,"Giarcoin"),            
    GLB(92,"Globe"),                
    GML(94,"GameleagueCoin"),       
    GNO(291,"Gnosis"),              
    GNS(95,"GenesisCoin"),          
    GNT(290,"Golem"),               
    GOLD(96,"GoldEagles"),          
    GPC(97,"GROUPCoin"),            
    GPUC(98,"GPU Coin"),            
    GRC(261,"Gridcoin Research"),   
    GRCX(99,"Gridcoin"),            
    GRS(100,"Groestlcoin"),         
    GUE(101,"Guerillacoin"),        
    H2O(102,"H2O Coin"),            
    HIRO(103,"Hirocoin"),           
    HOT(104,"Hotcoin"),             
    HUC(105,"Huntercoin"),          
    HUGE(260,"BIGcoin"),            
    HVC(106,"Heavycoin"),           
    HYP(107,"HyperStake"),          
    HZ(108,"Horizon"),              
    IFC(109,"Infinitecoin"),        
    INDEX(265,"CoinoIndex"),        
    IOC(263,"IO Digital Currency"), 
    ITC(110,"Information Coin"),    
    IXC(111,"iXcoin"),              
    JLH(112,"jl777hodl"),           
    JPC(113,"JackpotCoin"),         
    JUG(114,"JuggaloCoin"),         
    KDC(115,"KlondikeCoin"),        
    KEY(116,"KeyCoin"),             
    LBC(280,"LBRY Credits"),        
    LC(117,"Limecoin"),             
    LCL(118,"Limecoin Lite"),       
    LEAF(119,"Leafcoin"),           
    LGC(120,"Logicoin"),            
    LOL(121,"LeagueCoin"),          
    LOVE(122,"LOVEcoin"),           
    LQD(123,"LIQUID"),              
    LSK(278,"Lisk"),                
    LTBC(124,"LTBCoin"),            
    LTC(125,"Litecoin"),            
    LTCX(126,"LiteCoinX"),          
    MAID(127,"MaidSafeCoin"),       
    MAST(128,"MastiffCoin"),        
    MAX(129,"MaxCoin"),             
    MCN(130,"Moneta Verde"),        
    MEC(131,"Megacoin"),            
    METH(132,"CryptoMETH"),         
    MIL(133,"Millennium Coin"),     
    MIN(134,"Minerals"),            
    MINT(135,"Mintcoin"),           
    MMC(136,"MemoryCoin"),          
    MMNXT(137,"MMNXT"),             
    MMXIV(138,"Maieuticoin"),       
    MNTA(139,"Moneta"),             
    MON(140,"Monocle"),             
    MRC(141,"microCoin"),           
    MRS(142,"Marscoin"),            
    MTS(144,"Metiscoin"),           
    MUN(145,"Muniti"),              
    MYR(146,"Myriadcoin"),          
    MZC(147,"MazaCoin"),            
    N5X(148,"N5coin"),              
    NAS(149,"NAS"),                 
    NAUT(150,"Nautiluscoin"),       
    NAV(151,"NAVCoin"),             
    NBT(152,"NuBits"),              
    NEOS(153,"Neoscoin"),           
    NL(154,"Nanolite"),             
    NMC(155,"Namecoin"),            
    NOBL(156,"NobleCoin"),          
    NOTE(157,"DNotes"),             
    NOXT(158,"NobleNXT"),           
    NRS(159,"NoirShares"),          
    NSR(160,"NuShares"),            
    NTX(161,"NTX"),                 
    NXC(288,"Nexium"),              
    NXT(162,"NXT"),                 
    NXTI(163,"NXTInspect"),         
    OMG(295,"OmiseGO"),             
    OMNI(143,"Omni"),               
    OPAL(164,"Opal"),               
    PAND(165,"PandaCoin"),          
    PASC(289,"PascalCoin"),         
    PAWN(166,"Pawncoin"),           
    PIGGY(167,"New Piggycoin"),     
    PINK(168,"Pinkcoin"),           
    PLX(169,"ParallaxCoin"),        
    PMC(170,"Premine"),             
    POT(171,"PotCoin"),             
    PPC(172,"Peercoin"),            
    PRC(173,"ProsperCoin"),         
    PRT(174,"Particle"),            
    PTS(175,"BitShares PTS"),       
    Q2C(176,"QubitCoin"),           
    QBK(177,"Qibuck"),              
    QCN(178,"QuazarCoin"),          
    QORA(179,"Qora"),               
    QTL(180,"Quatloo"),             
    RADS(274,"Radium"),             
    RBY(181,"Rubycoin"),            
    RDD(182,"Reddcoin"),            
    REP(284,"Augur"),               
    RIC(183,"Riecoin"),             
    RZR(184,"Razor"),               
    SBD(282,"Steem Dollars"),       
    SC(268,"Siacoin"),              
    SDC(185,"Shadow"),              
    SHIBE(186,"ShibeCoin"),         
    SHOPX(187,"ShopX"),             
    SILK(188,"Silkcoin"),           
    SJCX(189,"Storjcoin X"),        
    SLR(190,"SolarCoin"),           
    SMC(191,"SmartCoin"),           
    SOC(192,"SocialCoin"),          
    SPA(193,"Spaincoin"),           
    SQL(194,"Squallcoin"),          
    SRCC(195,"SourceCoin"),         
    SRG(196,"Surge"),               
    SSD(197,"Sonic"),               
    STEEM(281,"STEEM"),             
    STR(198,"Stellar"),             
    STRAT(287,"Stratis"),           
    SUM(199,"SummerCoin"),          
    SUN(200,"Suncoin"),             
    SWARM(201,"SWARM"),             
    SXC(202,"Sexcoin"),             
    SYNC(203,"Sync"),               
    SYS(204,"Syscoin"),             
    TAC(205,"Talkcoin"),            
    TOR(206,"TorCoin"),             
    TRUST(207,"TrustPlus"),         
    TWE(208,"Twecoin"),             
    UIS(209,"Unitus"),              
    ULTC(210,"Umbrella-LTC"),       
    UNITY(211,"SuperNET"),          
    URO(212,"Uro"),                 
    USDE(213,"USDE"),               
    USDT(214,"Tether USD"),         
    UTC(215,"UltraCoin"),           
    UTIL(216,"UtilityCoin"),        
    UVC(217,"UniversityCoin"),      
    VIA(218,"Viacoin"),             
    VOOT(219,"VootCoin"),           
    VOX(276,"Voxels"),              
    VRC(220,"VeriCoin"),            
    VTC(221,"Vertcoin"),            
    WC(222,"WhiteCoin"),            
    WDC(223,"Worldcoin"),           
    WIKI(224,"Wikicoin"),           
    WOLF(225,"InsanityCoin"),       
    X13(226,"X13Coin"),             
    XAI(227,"Sapience AIFX"),       
    XAP(228,"API Coin"),            
    XBC(229,"BitcoinPlus"),         
    XC(230,"XCurrency"),            
    XCH(231,"ClearingHouse"),       
    XCN(232,"Cryptonite"),          
    XCP(233,"Counterparty"),        
    XCR(234,"Crypti"),              
    XDN(235,"DigitalNote"),         
    XDP(236,"Dogeparty"),           
    XEM(256,"NEM"),                 
    XHC(237,"Honorcoin"),           
    XLB(238,"Libertycoin"),         
    XMG(239,"Magi"),                
    XMR(240,"Monero"),              
    XPB(241,"Pebblecoin"),          
    XPM(242,"Primecoin"),           
    XRP(243,"Ripple"),              
    XSI(244,"Stability Shares"),    
    XST(245,"StealthCoin"),         
    XSV(246,"Silicon Valley Coin"), 
    XUSD(247,"CoinoUSD"),           
    XVC(253,"Vcash"),               
    XXC(248,"CREDS"),               
    YACC(249,"YACCoin"),            
    YANG(250,"Yangcoin"),           
    YC(251,"YellowCoin"),           
    YIN(252,"Yincoin"),             
    ZEC(286,"Zcash"),               
    ZRX(293,"0x");                

    private Integer id;
    private String currencyName;
    
    CurrencyEnum(Integer id, String currencyName) {
        this.id = id;
        this.currencyName = currencyName;
    }

    public Integer id() {
        return id;
    }
    public String currencyName() {
        return currencyName;
    }
}
